# Generated by Django 4.2.7 on 2023-11-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CreatedDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UpdatedDate',
            new_name='updated_date',
        ),
    ]
